package it.polimi.ingsw.controller;

import it.polimi.ingsw.events.clientmessages.*;

public class GameHandler {

    public void start(){

    }

    public void process(String nickname, ClientMessage message){
        //to implement, instanceof for each message generated by the client
        if(message instanceof StartGame) {start();}
        else if(message instanceof SelectLeaderCards) {/*model methods*/}
        else if(message instanceof TakeResources) {}
        else if(message instanceof BuyCard) {}
        else if(message instanceof ActivateLeaderCard) {}
        else if(message instanceof EndTurn) {}
    }
}
